export const NEW_GAME = 'NEW_GAME';
export const JOIN_GAME = 'JOIN_GAME';
export const PLAYER_READY = 'PLAYER_READY';
export const TOGGLE_GAME_CREATED_MODAL = 'TOGGLE_GAME_CREATED_MODAL';
export const TOGGLE_JOIN_GAME_MODAL = 'TOGGLE_JOIN_GAME_MODAL';